### ISSUE TITLE
[FEAT] 네트워크 메소드 정리 및 홈 화면 구현

### ISSUE THREAD

**Issue by SnowMate318** [MealTokTok/MealTokTok-App#13]
## 🌴 작업 브랜치 
taehyun 브랜치
## 💼 TASK 개요 

네트워크 요청 관련 메소드 작성
홈 화면 ui 수정 및 API 연결

## ✅ TODO 및 진행현황 

- [x] 네트워크 요청 메소드 생성하기
- [x] signup api를 통해 access token, refresh token 받아서 관리하기
- [x] login api를 통해 access token, refresh token 받아서 관리하기
- [x] 홈 화면 bottom nav bar 수정하기
- [x] app bar 아이콘을 뱃지 형태로 만들기
- [ ] 알림 수신 시 알림 아이콘에 뱃지 숫자 추가하기
- [ ] 아이콘 클릭 시, 화면 이동과 함께 뱃지 숫자 초기화

- [ ] 홈 화면과 api 연결
